core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('playlist.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

playlist/urls.py
from django.urls import path
from .views import *

app_name = 'playlist'

urlpatterns = [
    path('', HomeViews, name='home'),
    path('video-down/', VideoPostView.as_view(), name='video-download-page'),
    # path('download/', youtube, name='download_video'),
    path('youtube/', home.as_view(),name="home-dev"),
    path('<slug:slug>/', VideoDetailView.as_view(), name='detail'),
]

playlist/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse


# Create your models here.
class VideoModel(models.Model):
    name = models.CharField(max_length=255, unique=True)
    video = models.FileField(upload_to='videos/')
    slug = models.SlugField(null=False, unique=True)
    joined_date = models.DateTimeField(auto_now=True)

    
    def get_absolute_url(self):
        return reverse("article_detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)
    
    def __str__(self) -> str:
        return self.name
    

playlist/forms.py
from django import forms
from .models import VideoModel


# create a ModelForm
class VideoModelForm(forms.ModelForm):
    class Meta:
        model = VideoModel
        fields = '__all__'

playlist/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.views.generic import DetailView, CreateView

from .forms import VideoModelForm
from .models import VideoModel


# Create your views here.
def home(req):
    return render(req, 'playlist/index.html', {'salom': 'salaomaaaa'})


def HomeViews(request):
    video=VideoModel.objects.all()
    return render(request, 'playlist/index.html', {'video': video})


class VideoDetailView(DetailView):
    model = VideoModel
    template_name = 'playlist/detail.html'
    context_object_name = 'video'


class VideoPostView(CreateView):
    model = VideoModel
    template_name = 'playlist/download.html'
    fields = ['name', 'video']
    success_url = '/'
    context_object_name= 'video'



# def VideoDownloadViews(request):
#     from pytube import YouTube                                    

#     video_url = 'https://youtube.com/shorts/SzxQByYBPjs?si=SHBTC41gXFhqDMhv'
#     yt = YouTube(video_url)
#     stream = yt.streams
#     vid = stream.get_by_itag(137)
#     # vid2 = yt.streams.get_highest_resolution()
#     vid.download()

#     print("Video downloaded successfully!")
#     return render(request, 'playlist/download.html')




#
# from pytube import YouTube
# from pytube.exceptions import RegexMatchError


# def download_video(request):
#     if request.method == 'POST':
#         link = request.POST['link']
#         try:
#             video = YouTube(link)
#             stream = video.streams.get_highest_resolution()
#             stream.download()
#             return render(request, 'playlist/success.html')
#         except RegexMatchError:
#             return render(request, 'playlist/video-down.html', {'error': 'Noto\'g\'ri URL manzili. Iltimos, to\'g\'ri URL manzilini kiriting.'})
#         except Exception as e:
#             return render(request, 'playlist/video-down.html', {'error': f'Xato yuz berdi: {str(e)}'})
#     return render(request, 'playlist/video-down.html')


# from pytube import *
  
  
# defining function 
# def youtube(request): 
  
#     # checking whether request.method is post or not 
#     if request.method == 'POST': 
        
#         # getting link from frontend 
#         link = request.POST['link'] 
#         video = YouTube(link) 
  
#         # setting video resolution 
#         stream = video.streams.get_highest_resolution() 
          
#         # downloads video 
#         stream.download() 
  
#         # returning HTML page 
#         return render(request, 'playlist/video-down.html') 
#     return render(request, 'playlist/video-down.html')



            ################################################          
from django.views.generic import View
from pytube import YouTube
from django.shortcuts import render,redirect


class home(View):
    def __init__(self,url=None):
        self.url = url

    def get(self,request):
        return render(request,'playlist/test1.html')  
    
    def post(self,request):
        # for fetching the video
        if request.POST.get('fetch-vid'):
            self.url = request.POST.get('given_url')
            video = YouTube(self.url)
            vidTitle,vidThumbnail = video.title,video.thumbnail_url
            qual,stream = [],[]
            for vid in video.streams.filter(progressive=True):
                qual.append(vid.resolution)
                stream.append(vid)
            context = {'vidTitle':vidTitle,'vidThumbnail':vidThumbnail,
                        'qual':qual,'stream':stream,
                        'url':self.url}
            return render(request,'playlist/test1.html',context)

        # for downloading the video
        elif request.POST.get('download-vid'):
            self.url = request.POST.get('given_url')
            video = YouTube(self.url)
            stream = [x for x in video.streams.filter(progressive=True)]
            video_qual = video.streams[int(request.POST.get('download-vid')) - 1] 
            video_qual.download(output_path='../../Downloads')
            return redirect('home-dev')

        return render(request,'playlist/test1.html')

templates/playlist/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
    {% block header %}<title>VideoPlaylist</title>
    {% endblock header %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <!-- google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand">
        <div class="container-fluid first">
            <a href="{% url 'playlist:home' %}"><img class="logo-img" src="{% static 'img/favicon.png' %}" alt="logo"></a>
        </div>
        <div class="search-div">
          <form class="d-flex" role="search">
            <input class="input me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="input btn btn-outline-secondary" type="submit">Search</button>
          </form>
        </div>
    
        <a href="" class="link-nav">Add</a>
        <a href="" class="link-nav">Playlist</a>
        <a href="" class="link-nav last">Profil</a>
      </nav>
    {% block content %}
    {% endblock content %}
</body>
</html>

templates/playlist/detail.html
{% extends 'playlist/base.html' %}
{% block header %}

{% endblock header %}

{% block content %}
<h1 class="video-name">{{ video.name }}</h1>
<video class="embed-responsive embed-responsive-16by9 videoclass" controls="controls">
    <source class="video-detail" src="{{ video.video.url }}" type="video/mp4">
</video>
{% endblock content %}

templates/playlist/index.html
{% extends 'playlist/base.html' %}
{% load static %}
{% block header %}
<title>VideoPlaylist</title>
{% endblock header %}

{% block content %}



<div class="container">
    {% for i in video %}
        <div class="video-con">
            <a class="video-name" href="{% url 'playlist:detail' slug=i.slug %}">{{ i.name }}</a>
            <video class="embed-responsive embed-responsive-16by9 videoclass" controls="controls">
                <source class="video-class" src="{{ i.video.url }}" type="video/mp4">
            </video>
        </div>
    {% endfor %}
</div>
{% endblock content %}